language: cpp
compiler:
  - gcc

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu precise main universe multiverse restricted'
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu quantal main universe multiverse restricted'
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu raring main universe multiverse restricted'
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu saucy main universe multiverse restricted'
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
- sudo apt-get update -qq
- sudo apt-get install qt5-default qttools5-dev-tools qtbase5-dev libqt5x11extras5-dev

script:
  - qmake -project
  - qmake qsc.pro
  - make
